#! /bin/bash

keyword="rgs-"

fullfile=$keyword"geneset-full"
extractedfile=$keyword"geneset-extracted"


refseq="../1-process-fastas/refseq-full.fasta"
extractedseq="../1-process-fastas/refseq-full-annotated.fasta"

cat $fullfile.fasta $refseq > $fullfile-AGS.fasta
cat $extractedfile.fasta $extractedseq > $extractedfile-AGS.fasta


